<?php
// hook_help
function first_mod_help($path,$arg){
  switch($path){
  case 'admin/help#first_mod':
    $output = "This is the help system";
    $output .= "this is more help";
    return $output;
    
  }
  }




function first_mod_permission(){
  return 
    array(
	  'access demo' => 
	  array(
		'title' => t('Access Drupal Camp Demo')
		)
	  );
}



//hook_menu
function first_mod_menu(){
  $items['foo1'] = 
    array(
	  'title' => 'A simple page',
	  'page callback' => 'foo1_page',
	  'access callback' => TRUE,
	  'type' => MENU_CALLBACK,
	  );

  $items['foo2'] = 
    array(
	  'title' => 'A simple page with permissions',
	  'page callback' => 'foo2_page',
	  'access callback' => 'user_access',
	  'access arguments' => array('access demo'),
	  'type' => MENU_CALLBACK,
	  );

  $items['myform'] = 
    array(
	  'title' => 'A simple form demo',
	  'page callback' => 'myform_page',
	  'access callback' => 'user_access',
	  'access arguments' => array('access demo'),
	  'type' => MENU_CALLBACK,
	  );

  $items['myform_result'] = 
    array(
	  'title' => 'Form submission results',
	  'page callback' => 'myform_results_page',
	  'access callback' => 'user_access',
	  'access arguments' => array('access demo'),
	  'type' => MENU_CALLBACK,
	  );

  
  return $items;
}


function foo1_page(){
  $markup = '';
  $markup .= "<h1>Heading 1</h1>";
  $markup .= "<p>And now a paragraph</p>";
  return array('#markup' => $markup);
}


function foo2_page(){
  $markup = '';
  $markup .= "<h1>A Page With Permissions</h1>";
  $markup .= "<p>And now a paragraph</p>";
  return array('#markup' => $markup);
}


function myform_page(){
  $markup = 'Here is our form:<br>';
  $foo = drupal_get_form('myformelements');
  $markup .= drupal_render($foo);
  return array('#markup' => $markup);
}



function myformelements(){
  $form = array();

  $form['first_name'] = array(
			      '#type' => 'textfield',
			      '#field_prefix' => 'Enter your first name:',
			      '#description' => 'Put Bob if your name is Bob',
			      '#weight' => 1,			      
			      '#attributes' => array(
						     'placeholder' => t('Bob')
						     ),			      
			      );

  
  $form['email'] = array(
			 '#type' => 'textfield',
			 '#field_prefix' => 'Enter your email:',
			 '#weight' => 2,
			 '#attributes' => array(
						'placeholder' => t('bob@example.com')
						),
    );


  $form['submit'] = array(
			  '#type' => 'submit',
			  '#value' => 'Put whatever you want here',
			  '#weight' => 3,
			  );



  $form['#validate'][] = 'my_validate_function';
  $form['#submit'][] = 'my_submit_function';

  return $form;
}




function my_validate_function($form,&$form_state){
  $email = $form_state['values']['email'];
  if( preg_match("/@/",$email) == 0 ) {
    form_set_error('email',t('Oops!  You need an @ symbol!'));
  }
}


function my_submit_function($form,&$form_state){
  $_SESSION['drupalcamp']['email'] = $form_state['values']['email'];
  $_SESSION['drupalcamp']['first_name'] = $form_state['values']['first_name'];
  $form_state['redirect'] = 'myform_result';
}



function myform_results_page(){
  $email = $_SESSION['drupalcamp']['email'];
  $first_name = $_SESSION['drupalcamp']['first_name'];


  $markup = '';

  
  //-------------------------------
  // demo db_select by getting max id
  
  $query = db_select('myform_data', 'md');
  $query->fields('md', array('id'));
  $ids = $query
    ->execute()
    ->fetchCol();

  $max_id = max($ids);
  $markup .= "<br>max id:$max_id";
  //-------------------------------^




  //-------------------------------
  // now let's push the data into the database

  $id = $max_id+1;

  $query = db_insert('myform_data')
    ->fields(array('id','email','first_name'));

  $query->values(array(
		       'id' => $id,
		       'email' => $email,
		       'first_name' => $first_name
		       ));
  
  $result = $query->execute();
  //-------------------------------^


  $markup .= "<br>First name: $first_name";
  $markup .= "<br>Email: $email";
  return array('#markup' => $markup);  
}

